import type { SaleReceiptResponse } from "@marketbook/shared/types";

function escapeHtml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

function money(value: string, currency: string): string {
  return `${escapeHtml(currency)} ${escapeHtml(value)}`;
}

export function renderSaleReceiptHtml(receipt: SaleReceiptResponse): string {
  const itemRows = receipt.items
    .map(
      (item) => `
        <tr>
          <td>${escapeHtml(item.name)}<small>${escapeHtml(item.quantity)} ${escapeHtml(item.unit)} × ${money(item.unitPrice, receipt.currency)}</small></td>
          <td class="amount">${money(item.lineTotal, receipt.currency)}</td>
        </tr>`,
    )
    .join("");

  const statusNotice =
    receipt.status === "VOIDED"
      ? '<div class="notice">VOIDED</div>'
      : receipt.refundedAmount !== "0.00"
        ? `<div class="notice">REFUNDED: ${money(receipt.refundedAmount, receipt.currency)}</div>`
        : "";

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Receipt ${escapeHtml(receipt.receiptNumber)}</title>
  <style>
    :root { color-scheme: light; font-family: ui-monospace, SFMono-Regular, Consolas, monospace; }
    * { box-sizing: border-box; }
    body { margin: 0; background: #f2f2f2; color: #111; }
    main { width: min(100%, 420px); margin: 24px auto; padding: 24px; background: #fff; }
    h1, .center { text-align: center; }
    h1 { margin: 0 0 6px; font: 700 22px system-ui, sans-serif; }
    p { margin: 4px 0; }
    .meta { margin: 20px 0; padding-block: 12px; border-block: 1px dashed #777; }
    table { width: 100%; border-collapse: collapse; }
    td { padding: 8px 0; vertical-align: top; border-bottom: 1px dotted #bbb; }
    small { display: block; margin-top: 3px; color: #555; }
    .amount { text-align: right; white-space: nowrap; }
    .totals { margin-top: 14px; }
    .row { display: flex; justify-content: space-between; gap: 16px; margin: 6px 0; }
    .total { font-weight: 700; font-size: 1.1rem; border-top: 2px solid #111; padding-top: 8px; }
    .notice { margin: 16px 0; padding: 10px; border: 2px solid #111; text-align: center; font-weight: 700; }
    footer { margin-top: 22px; text-align: center; font-size: .85rem; color: #555; }
    @media print { body { background: #fff; } main { width: 80mm; margin: 0; padding: 6mm; } }
  </style>
</head>
<body>
  <main>
    <header class="center">
      <h1>${escapeHtml(receipt.business.name)}</h1>
      <p>Receipt ${escapeHtml(receipt.receiptNumber)}</p>
    </header>
    ${statusNotice}
    <section class="meta">
      <p>Date: ${escapeHtml(new Date(receipt.soldAt).toLocaleString("en-SL", { timeZone: "Africa/Freetown" }))}</p>
      <p>Customer: ${escapeHtml(receipt.customerName ?? "Walk-in customer")}</p>
      <p>Served by: ${escapeHtml(receipt.servedBy)}</p>
    </section>
    <table><tbody>${itemRows}</tbody></table>
    <section class="totals">
      <div class="row"><span>Subtotal</span><span>${money(receipt.subtotal, receipt.currency)}</span></div>
      <div class="row"><span>Discount</span><span>${money(receipt.discountAmount, receipt.currency)}</span></div>
      <div class="row total"><span>Total</span><span>${money(receipt.totalAmount, receipt.currency)}</span></div>
      <div class="row"><span>Paid</span><span>${money(receipt.amountPaid, receipt.currency)}</span></div>
      <div class="row"><span>Wallet</span><span>${money(receipt.walletAmountUsed, receipt.currency)}</span></div>
      <div class="row"><span>Outstanding</span><span>${money(receipt.outstandingAmount, receipt.currency)}</span></div>
    </section>
    <footer><p>Thank you for your business.</p><p>Generated by MarketBook SL</p></footer>
  </main>
</body>
</html>`;
}
