export const PAYMENT_ERROR_CODES = {
  PAYMENT_PROVIDER_NOT_CONFIGURED: "PAYMENT_PROVIDER_NOT_CONFIGURED",
  PAYMENT_PROVIDER_UNAVAILABLE: "PAYMENT_PROVIDER_UNAVAILABLE",
  PAYMENT_NOT_FOUND: "PAYMENT_NOT_FOUND",
  PAYMENT_ALREADY_COMPLETED: "PAYMENT_ALREADY_COMPLETED",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  PAYMENT_EXPIRED: "PAYMENT_EXPIRED",
  PAYMENT_PENDING: "PAYMENT_PENDING",
  PAYMENT_AMOUNT_INVALID: "PAYMENT_AMOUNT_INVALID",
  PAYMENT_VERIFICATION_FAILED: "PAYMENT_VERIFICATION_FAILED",
  PAYMENT_IDEMPOTENCY_CONFLICT: "PAYMENT_IDEMPOTENCY_CONFLICT",
  PAYMENT_RESERVATION_EXPIRED: "PAYMENT_RESERVATION_EXPIRED",
  INSUFFICIENT_AVAILABLE_STOCK: "INSUFFICIENT_AVAILABLE_STOCK",
  INSUFFICIENT_WALLET_BALANCE: "INSUFFICIENT_WALLET_BALANCE",
  PAYMENT_PROVIDER_UNSUPPORTED: "PAYMENT_PROVIDER_UNSUPPORTED",
  PAYMENT_CALLBACK_INVALID: "PAYMENT_CALLBACK_INVALID",
} as const;

export type PaymentErrorCode =
  (typeof PAYMENT_ERROR_CODES)[keyof typeof PAYMENT_ERROR_CODES];
